---
# tasks file for dockerapp
#  
- name: build image
  docker_image: 
    name: "{{app_name}}:{{app_version}}"
    source: build
    build:
      path: /var/lib/jenkins/workspace/ansible
    

- name: create container
  docker_container:
    name: "{{app_name}}"
    image: "{{app_name}}:{{app_version}}"
    ports: 
      - "{{port}}"  
    state: started  
      
